Readme
Tejinder15/QuizBuzz pull request #6
Opened 2022-02-19 17:09 UTC by Tejinder15

# Created Readme File

2022-02-19 17:20 UTC, Meghana-sk requested changes

2022-02-19 17:20 UTC, Meghana-sk commented on README.md
> +## Tecnologies Used
Please fix typo for `Technologies`

2022-02-19 17:31 UTC, kart-c approved these changes

2022-02-20 05:33 UTC, Meghana-sk approved these changes
Good job Tajinder. Go ahead with the merge.

2022-02-20 06:21 UTC, merged